spring.application.name=Backend
spring.datasource.url=jdbc:h2:mem:creditdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.port=8085

# Désactiver la configuration de sécurité automatique
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Configuration JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
app.jwt.secret=JWTSuperSecretKey123456789012345678901234567890123456789012345678901234567890
app.jwt.expiration=86400000 

# Swagger configuration
springfox.documentation.swagger.v3.path=/v2/api-docs